### ISSUE TITLE
Make lv2:Plugin a subclass of doap:Project

### ISSUE THREAD

**Issue by falkTX** [lv2/lv2#3]
LV2 plugins need to use some doap properties to identify the plugin (like doap:name), but without the plugin being a doap:Project having those values kinda breaks the rules.

I know this might be a bit tricky, but considering LV2 requires a doap:name in each plugin, I think it makes sense.
Also, without doap:Project subclass, developer and maintainer are considered invalid by sord_validate:

```
error: Subject not in property domain:
       http://moddevices.com/plugins/caps/CabinetIII
       http://usefulinc.com/ns/doap#developer
       b721
note: Domain is <http://usefulinc.com/ns/doap#Project>
error: Subject not in property domain:
       http://moddevices.com/plugins/caps/CabinetIII
       http://usefulinc.com/ns/doap#maintainer
       b722
note: Domain is <http://usefulinc.com/ns/doap#Project>
```

**Comment by falkTX** [comment]
Here's a patch-fix:
```
From 0c8b704450019e6cb0fab2794b884e1cbb536e95 Mon Sep 17 00:00:00 2001
From: falkTX <falktx@gmail.com>
Date: Wed, 1 Jul 2015 14:53:48 +0200
Subject: [PATCH] make lv2:Plugin a subclass of doap:Project so that we can use
 doap properties on plugins

---
 lv2/lv2plug.in/ns/lv2core/lv2core.ttl | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/lv2/lv2plug.in/ns/lv2core/lv2core.ttl b/lv2/lv2plug.in/ns/lv2core/lv2core.ttl
index 7434aa0..723f6dc 100644
--- a/lv2/lv2plug.in/ns/lv2core/lv2core.ttl
+++ b/lv2/lv2plug.in/ns/lv2core/lv2core.ttl
@@ -139,7 +139,8 @@ hosts and other tools already <q>understand</q> this structure.</p>
 lv2:Plugin
 	a rdfs:Class ,
 		owl:Class ;
-	rdfs:subClassOf lv2:PluginBase ;
+	rdfs:subClassOf lv2:PluginBase ,
+		doap:Project ;
 	rdfs:label "Plugin" ;
 	rdfs:subClassOf [
 		a owl:Restriction ;
```

**Comment by falkTX** [comment]
I can do a github pull request, but I figured this would need some discussion first..

**Comment by drobilla** [comment]
I don't think this is really appropriate.  doap:Project is a project with its own homepage, source repository, and so on.  This is true for some plugins, but not all.  Many, if not most, plugins, are part of a project with several plugins (or other things), which is described by linking to the project description with lv2:project.

An individual plugin can always make itself a doap:Project.

Then again, LV2 does dictate the use of doap properties, as you say.  This was a mistake (I don't know how we ended up on enough crack to use the crazy plethora of name/label properties we did), but is reality... I don't know :/

**Comment by falkTX** [comment]
Well, for MOD all plugins will pass through a verification and sord_validate is one of them.
I don't think plugin developers are expecting to create a doap:Project, at least I wasn't.

Is this documented somewhere?

btw, how can sord_validate consider doap:name on a lv2:Plugin valid, but not doap:developer?

**Comment by badosu** [comment]
@falkTX not really related to the doap issue, but since you're doing a validation check you might find `lv2_validate` useful.

**Comment by falkTX** [comment]
I already have such script.
```
$ cat /usr/bin/sord_validate_lv2 
#!/bin/bash

if [ "$1"x == ""x ]; then
  echo "usage: $0 /path/to/bundle"
  exit
fi

if [ ! -d /usr/lib/lv2/meta ]; then
  echo "/usr/lib/lv2/meta directory is missing"
  exit
fi

if [ ! -d /usr/lib/lv2/schemas.lv2 ]; then
  echo "/usr/lib/lv2/schemas.lv2 directory is missing"
  exit
fi

# don't check all lv2 bundles, if atom.lv2 is installed the others should be too
if [ ! -d /usr/lib/lv2/atom.lv2 ]; then
  echo "/usr/lib/lv2/atom.lv2 directory is missing"
  exit
fi

if [ -d /usr/lib/lv2/mod.lv2 ]; then
  EXT_MOD="/usr/lib/lv2/mod.lv2"
fi

if [ -d /usr/lib/lv2/modgui.lv2 ]; then
  EXT_MODGUI="/usr/lib/lv2/modgui.lv2"
fi

if [ -d /usr/lib/lv2/modpedal.lv2 ]; then
  EXT_MODPEDAL="/usr/lib/lv2/modpedal.lv2"
fi

if [ -d /usr/lib/lv2/kx-meta ]; then
  KX_META="/usr/lib/lv2/kx-meta"
fi

if [ -d /usr/lib/lv2/kx-external-ui.lv2 ]; then
  KX_EXTUI="/usr/lib/lv2/kx-external-ui.lv2"
fi

if [ -d /usr/lib/lv2/kx-programs.lv2 ]; then
  KX_PROGS="/usr/lib/lv2/kx-programs.lv2"
fi

if [ -d /usr/lib/lv2/kx-rtmempool.lv2 ]; then
  KX_RTMPL="/usr/lib/lv2/kx-rtmempool.lv2"
fi

exec sord_validate $(find \
  /usr/lib/lv2/meta \
  /usr/lib/lv2/{atom,buf-size,data-access,dynmanifest,event,instance-access,log,lv2core,midi,morph,options,parameters,patch,port-groups,port-props,presets,resize-port,schemas,state,time,ui,units,urid,uri-map,worker}.lv2 \
  $EXT_MOD \
  $EXT_MODGUI \
  $EXT_MODPEDAL \
  $KX_META \
  $KX_EXTUI \
  $KX_PROGS \
  $KX_RTMPL \
  -name '*.ttl') $(find "$@" -name '*.ttl')
```
The one I have uses the kxstudio and mod extensions if installed.

**Comment by drobilla** [comment]
Not all plugins are projects, only some are.  So closing this as not a vocabulary issue.
