### ISSUE TITLE
"git clone --recursive" doesn't work

### ISSUE THREAD

**Issue by jofemodo** [lv2/lv2#43]
git clone --recursive https://github.com/drobilla/lv2.git
Cloning into 'lv2'...
remote: Enumerating objects: 851, done.
remote: Counting objects: 100% (851/851), done.
remote: Compressing objects: 100% (397/397), done.
remote: Total 10829 (delta 575), reused 692 (delta 452), pack-reused 9978
Receiving objects: 100% (10829/10829), 6.21 MiB | 294.00 KiB/s, done.
Resolving deltas: 100% (6855/6855), done.
Submodule 'waflib' (https://github.com/drobilla/autowaf.git) registered for path 'waflib'
Cloning into '/home/pi/zynthian-sw/lv2/waflib'...
remote: Enumerating objects: 33, done.        
remote: Counting objects: 100% (33/33), done.        
remote: Compressing objects: 100% (28/28), done.        
remote: Total 1070 (delta 8), reused 17 (delta 5), pack-reused 1037        
Receiving objects: 100% (1070/1070), 1.27 MiB | 282.00 KiB/s, done.
Resolving deltas: 100% (586/586), done.
fatal: remote error: upload-pack: not our ref 878bdba53979f11fa582088e47997df129e56d16
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'waflib', but it did not contain 878bdba53979f11fa582088e47997df129e56d16. Direct fetching of that commit failed.

**Comment by jofemodo** [comment]
Building from the last release tarball doesn't work either:

```
wget https://github.com/lv2/lv2/archive/v1.18.0.tar.gz
tar xfvz v1.18.0.tar.gz
cd  lv2-1.18.0
./waf configure
error: Failed to import waf (No module named waflib)

```

**Comment by mfisher31** [comment]
@jofemodo - Maybe using the new URL will work:  https://github.com/lv2/lv2.git.  Git might be confused with Github redirecting from `drobilla`

For the second problem: Github tarball's don't include submodules.

**Comment by drobilla** [comment]
Yes, the repository has moved to the lv2 organization, and apparently the warning does not display in this case.

As far as I can tell there is no way to make github release archives work, _and_ no way to just turn them off, which is incredibly annoying...

**Comment by jofemodo** [comment]
Using the lv2 organization's URl doesn't improve things:

```
git clone --recursive https://github.com/lv2/lv2.git
Cloning into 'lv2'...
remote: Enumerating objects: 851, done.
remote: Counting objects: 100% (851/851), done.
remote: Compressing objects: 100% (397/397), done.
remote: Total 10829 (delta 575), reused 692 (delta 452), pack-reused 9978
Receiving objects: 100% (10829/10829), 6.21 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (6855/6855), done.
Submodule 'waflib' (https://github.com/drobilla/autowaf.git) registered for path 'waflib'
Cloning into '/home/pi/zynthian-sw/lv2/waflib'...
remote: Enumerating objects: 33, done.        
remote: Counting objects: 100% (33/33), done.        
remote: Compressing objects: 100% (28/28), done.        
remote: Total 1070 (delta 8), reused 17 (delta 5), pack-reused 1037        
Receiving objects: 100% (1070/1070), 1.27 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (586/586), done.
fatal: remote error: upload-pack: not our ref 878bdba53979f11fa582088e47997df129e56d16
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'waflib', but it did not contain 878bdba53979f11fa582088e47997df129e56d16. Direct fetching of that commit failed.

```
The problem also affects other libraries, like serd, sord, sratom, suil, lilv, etc.

**Comment by jofemodo** [comment]
And note that using the source code tarball doesn't work:

`https://github.com/lv2/lv2/archive/v1.18.0.tar.gz`

as i commented above ...

**Comment by jofemodo** [comment]
I checked, and the referenced commit:

878bdba53979f11fa582088e47997df129e56d16

doesn't exist on autowaf repo:

https://github.com/drobilla/autowaf.git

**Comment by mfisher31** [comment]
This may have something to do with it.
https://github.com/lv2/lv2/blob/bf6b8468790382bd26dfb614936f788ec82f6b9e/.gitmodules#L3

**Comment by drobilla** [comment]
Oh, the github mirror was stale.  Updated.

```
$ git clone --recursive https://github.com/lv2/lv2.git
Cloning into 'lv2'...
remote: Enumerating objects: 851, done.
remote: Counting objects: 100% (851/851), done.
remote: Compressing objects: 100% (397/397), done.
remote: Total 10829 (delta 575), reused 692 (delta 452), pack-reused 9978
Receiving objects: 100% (10829/10829), 6.21 MiB | 4.57 MiB/s, done.
Resolving deltas: 100% (6855/6855), done.
Submodule 'waflib' (https://github.com/drobilla/autowaf.git) registered for path 'waflib'
Cloning into '/home/drobilla/src/test/lv2/waflib'...
remote: Enumerating objects: 37, done.        
remote: Counting objects: 100% (37/37), done.        
remote: Compressing objects: 100% (30/30), done.        
remote: Total 1074 (delta 10), reused 20 (delta 7), pack-reused 1037        
Receiving objects: 100% (1074/1074), 1.28 MiB | 2.60 MiB/s, done.
Resolving deltas: 100% (588/588), done.
Submodule path 'waflib': checked out '878bdba53979f11fa582088e47997df129e56d16'
```
