### ISSUE TITLE
Please mark ui:resize as deprecated

### ISSUE THREAD

**Issue by falkTX** [lv2/lv2#57]
Following from the conversation on https://github.com/lv2/pugl/issues/42

Please mark https://lv2plug.in/ns/extensions/ui#resize as deprecated, it will be the first step to stop people using it.

The child window resize detection was already confirmed to be possible on X11.
I have seen similar code on macOS and Windows, though I have not tried this yet.

Are there any left-over concerns?

**Comment by drobilla** [comment]
7459cc2
