### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by falkTX** [lv2/lv2#60]
The latest stable release is 1.18.2, and there have been a few changes made since then.
For example https://github.com/lv2/lv2/commit/ba34a58b32839491335b5bcbda46e11c4b209cbc which defines `LV2_CORE__enabled` that was missing, plus some metadata/syntax improvements.

For packaging, would be nice to have all the recent things in a tagged release.
I have been using the latest git/HEAD without issues, it is just nicer to have it as part of a release.
Thanks

**Comment by drobilla** [comment]
d97a1a4
