### ISSUE TITLE
Cannot build old releases due to autowaf repository deletion

### ISSUE THREAD

**Issue by falkTX** [lv2/lv2#63]
For reproducible builds, it is important to keep old releases working, so final binaries remain mostly the same no matter who and when we build things.
Sadly this is no longer possible for the lv2 project when using a git hash as version, failing as such:

```
HEAD is now at d97a1a4 LV2 1.18.4
fatal: repository '../../drobilla/autowaf.git' does not exist
fatal: clone of '../../drobilla/autowaf.git' into submodule path '/tmp/mbs/moddwarf/plugins-dep/build/lv2-d97a1a4daff228bdd62c68859959d13077e47026/waflib' failed
Failed to clone 'waflib'. Retry scheduled
fatal: repository '../../drobilla/autowaf.git' does not exist
fatal: clone of '../../drobilla/autowaf.git' into submodule path '/tmp/mbs/moddwarf/plugins-dep/build/lv2-d97a1a4daff228bdd62c68859959d13077e47026/waflib' failed
Failed to clone 'waflib' a second time, aborting
```

**Comment by drobilla** [comment]
That's what tarballs are for.

**Comment by falkTX** [comment]
I get it, but sometimes there are fixes in git versions of lv2 that dont make it into a release much later, as was the case recently.
I now changed to a tarball that kinda matches the version I had before, but it is still a surprise when builds dont work because whole repositories are deleted.

**Comment by drobilla** [comment]
Fair enough.  However, LV2 git (and all the ops and testing) "officially" lives at Gitlab.  If you want a dependable git source, use that one.  Autowaf still exists there as https://gitlab.com/drobilla/autowaf/ and I won't delete it.

I can perhaps revive the Github autowaf one (later), but it's better to use the Gitlab one anyway.  Things sometimes get out of sync on the Github mirror anyway because I have to remember to explicitly push to it.

**Comment by falkTX** [comment]
huh I thought it was using the same autowaf for both due to git submodules, but I guess the old setup was different.

**Comment by drobilla** [comment]
The submodule URI should be relative so it works on whatever host.

Also, hm: https://github.com/drobilla/autowaf

Did you have a super old checkout that was pulling it from drobilla.net or something?  I've been working on sorting out this messy distinction between LV2 and "drobilla stuff" (meson certainly helped there) but it was a bit of a mess in the past.

**Comment by falkTX** [comment]
I was using cd152104c84bcee9fec22ef780cec2af7ba85d0c from this repo.
Anyhow, the cleanup surely is a nice step.

**Comment by drobilla** [comment]
$ git clone git@github.com:lv2/lv2.git
    Cloning into 'lv2'...
    [...]
    
    $ cd lv2
    drobilla@tesla ~/src/temp/lv2 [master]
    
    $ git checkout cd15210
    [...]
    HEAD is now at cd15210 LV2 1.18.2
    
    $ git submodule update --init --recursive
    Submodule 'waflib' (git@github.com:drobilla/autowaf.git) registered for path 'waflib'
    Cloning into '/home/drobilla/src/temp/lv2/waflib'...
    Submodule path 'waflib': checked out 'b600c928b221a001faeab7bd92786d0b25714bc8'
    
    $ ./waf configure
    Setting top to                                : /home/drobilla/src/temp/lv2
    [...]
    'configure' finished successfully (0.400s)
    
and

    $ git clone https://github.com/lv2/lv2.git
    Cloning into 'lv2'...
    [...]

    $ cd lv2

    $ git checkout cd15210
    [...]
    HEAD is now at cd15210 LV2 1.18.2

    $ git submodule update --init --recursive
    Submodule 'waflib' (https://github.com/drobilla/autowaf.git) registered for path 'waflib'
    Cloning into '/home/drobilla/src/temp/lv2/waflib'...
    Submodule path 'waflib': checked out 'b600c928b221a001faeab7bd92786d0b25714bc8'

    $ ./waf configure
    Setting top to                                : /home/drobilla/src/temp/lv2
    [...]
    'configure' finished successfully (0.333s)

Nothing has changed here as far as I can tell.
