### ISSUE TITLE
LV2:Worker thread racing guarantees

### ISSUE THREAD

**Issue by sadko4u** [lv2/lv2#69]
Consider the following case:

1. Some thread submits a job from run() method.
2. The job is put into hosts' queue.
3. The host stops plugin execution and calls the plugin for destruction.
4. The job is taken from the queue by some thread and some non-RT thread of the host starts it's execution.

Such scenario can yield to data racing and, I think, should be clarified in documentation. The main questions are:
1. How real this case is?
2. Are there any guarantees that the host won't execute the job if plugin is called for destruction?

**Comment by drobilla** [comment]
> How real this case is?

Seems possible, but rather unlikely in practice.

> Are there any guarantees that the host won't execute the job if plugin is called for destruction?

Not written down, but it seems there's only one reasonable position here: this is a host bug, destroyed plugins can't be expected to do anything, they're destroyed.  I'm not sure how easy this would be to do in multi-plugin hosts, it depends on their architecture.
