### ISSUE TITLE
LV2_Midi_Controller in struct, then sizeof(struct) produces strange size

### ISSUE THREAD

**Issue by WhiteGobo** [lv2/lv2#71]
If i create a struct from `LV2_Midi_Controller` i get a size of 8. i would expect a size 1.
I dont know much about midi or C but this seems wrong to me.

```C
typedef struct {
        LV2_Midi_Controller ctl_msg;
} ControllerMsg;

//sizeof(ControllerMsg) == 8
//i would expect 1
```

**Comment by mfisher31** [comment]
If the enum is represented by the compiler as a 64 bit integer, then sizeof being 8 makes perfect sense.

**Comment by drobilla** [comment]
> i would expect a size 1

That's not how C enums work.  If you want to constrict the size of an enum field, you either need to use the appropriate plain integer datatype for it (`uint8_t` in this case) or a field width specifier.
